# Generated by Django 3.1.1 on 2021-10-18 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc', models.CharField(max_length=40)),
                ('num_doc', models.CharField(max_length=15)),
                ('ape_pat', models.CharField(max_length=40)),
                ('ape_mat', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=50)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(max_length=10, null=True)),
                ('estado', models.CharField(default=1, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_exam', models.CharField(max_length=50, null=True)),
                ('archivo_exam', models.FileField(null=True, upload_to='media/')),
                ('estado_lectura', models.CharField(max_length=30, null=True)),
                ('estado', models.CharField(default='1', max_length=5)),
                ('fecha_reg', models.DateTimeField(auto_now_add=True)),
                ('user_reg', models.CharField(max_length=40, null=True)),
                ('fecha_mod', models.DateTimeField(null=True)),
                ('user_mod', models.CharField(max_length=50, null=True)),
                ('fecha_eli', models.DateTimeField(null=True)),
                ('user_eli', models.CharField(max_length=50, null=True)),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Asistencial.paciente')),
            ],
        ),
    ]
