# Generated by Django 3.1.1 on 2022-05-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codCas', models.CharField(max_length=15, unique=True)),
                ('descripCas', models.CharField(max_length=50)),
            ],
        ),
    ]
