# Generated by Django 3.1.1 on 2021-10-18 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.paciente'),
        ),
    ]
