# Generated by Django 3.1.1 on 2021-10-18 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0002_auto_20211018_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numHisCli', models.CharField(max_length=30, null=True)),
                ('numBalda', models.CharField(max_length=30, null=True)),
                ('estado', models.CharField(default='1', max_length=5)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.paciente')),
            ],
        ),
    ]
