# Generated by Django 3.1.1 on 2022-05-20 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0002_cas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.cas'),
        ),
    ]
