# Generated by Django 3.1.1 on 2021-10-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0003_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='user_reg',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
