# Generated by Django 3.1.1 on 2022-05-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0004_auto_20220523_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='casOri',
            field=models.CharField(default=401, max_length=10),
            preserve_default=False,
        ),
    ]
