# Generated by Django 3.1.1 on 2021-10-26 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0004_archivo_user_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='ambiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codAmb', models.CharField(max_length=11)),
                ('descAmb', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='bienpat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codEti', models.CharField(max_length=30, unique=True)),
                ('propBien', models.CharField(default='ESSALUD', max_length=50)),
                ('desBien', models.CharField(max_length=100)),
                ('serBien', models.CharField(max_length=50)),
                ('modBien', models.CharField(max_length=15)),
                ('marBien', models.CharField(max_length=15)),
                ('situBien', models.CharField(default='B', max_length=5)),
                ('valBien', models.IntegerField(default=0)),
                ('estBien', models.CharField(default=1, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='dependencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codDep', models.CharField(max_length=20, unique=True)),
                ('descDep', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dniPer', models.CharField(max_length=8, unique=True)),
                ('apePatPer', models.CharField(max_length=50)),
                ('apeMatPer', models.CharField(max_length=50)),
                ('nomPer', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=50)),
                ('fecNacPer', models.DateField(null=True)),
                ('codPlaPer', models.CharField(max_length=50)),
                ('regPer', models.CharField(max_length=50)),
                ('areaPer', models.CharField(max_length=50)),
                ('cargoPer', models.CharField(max_length=50)),
                ('nivelPer', models.CharField(max_length=50)),
                ('telefoPer', models.CharField(max_length=50)),
                ('correoPer', models.CharField(max_length=50)),
                ('direcPer', models.CharField(max_length=50)),
                ('estPer', models.CharField(default=1, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='bienPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bienpat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.bienpat')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.personal')),
            ],
        ),
        migrations.CreateModel(
            name='bienImag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='fotos/')),
                ('bienpat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.bienpat')),
            ],
        ),
        migrations.CreateModel(
            name='bienAmbiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.ambiente')),
                ('bienpat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.bienpat')),
            ],
        ),
        migrations.AddField(
            model_name='ambiente',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.dependencia'),
        ),
    ]
