# Generated by Django 3.1.1 on 2022-05-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0005_paciente_casori'),
    ]

    operations = [
        migrations.AddField(
            model_name='cas',
            name='tipoCas',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
