# Generated by Django 3.1.1 on 2021-10-27 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0007_auto_20211027_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='provMaq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usobien', models.CharField(max_length=5)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.paciente')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.proveedor')),
            ],
        ),
    ]
