# Generated by Django 3.1.1 on 2022-06-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0007_auto_20220527_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutricion',
            name='pacNuevo',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
