# Generated by Django 3.1.1 on 2022-06-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0008_nutricion_pacnuevo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutricion',
            name='fechaEvaluacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutricion',
            name='fechaIngreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutricion',
            name='porcentajeEPT',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
