# Generated by Django 3.1.1 on 2021-10-27 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0009_provmaq_bienpat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provmaq',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='provmaq',
            name='proveedor',
        ),
    ]
