# Generated by Django 3.1.1 on 2022-06-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0009_auto_20220627_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutricion',
            name='pacNuevo',
            field=models.BooleanField(),
        ),
    ]
