# Generated by Django 3.1.1 on 2021-10-27 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0010_auto_20211027_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provmaq',
            name='bienpat',
        ),
    ]
