# Generated by Django 3.1.1 on 2022-07-01 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0010_auto_20220627_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='casOri',
            new_name='cas',
        ),
    ]
