# Generated by Django 3.1.1 on 2022-07-04 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0011_auto_20220701_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='presanemia',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Asistencial.usuario'),
            preserve_default=False,
        ),
    ]
