# Generated by Django 3.1.1 on 2022-07-04 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0012_presanemia_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='admianemia',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Asistencial.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exclusionanemia',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Asistencial.usuario'),
            preserve_default=False,
        ),
    ]
