# Generated by Django 3.1.1 on 2022-07-07 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0013_auto_20220704_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='personalVpn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=30, null=True)),
                ('usuario', models.CharField(max_length=30)),
                ('clave', models.CharField(max_length=30)),
                ('personalAutoriza', models.CharField(max_length=40)),
                ('fechaHabilita', models.DateField(blank=True, null=True)),
                ('fechaInstalacion', models.DateField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_reg', models.DateTimeField(auto_now=True)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.personal')),
            ],
        ),
        migrations.DeleteModel(
            name='personalVpnAct',
        ),
    ]
