# Generated by Django 3.1.1 on 2022-08-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0014_auto_20220707_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='delegacionBienesEstra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solPed', models.CharField(blank=True, max_length=30, null=True)),
                ('codigoSap', models.CharField(blank=True, max_length=30, null=True)),
                ('producto', models.CharField(blank=True, max_length=150, null=True)),
                ('unidadMedida', models.CharField(blank=True, max_length=15, null=True)),
                ('cantidad', models.IntegerField()),
                ('fechaDelegacion', models.DateField(blank=True, null=True)),
                ('fechaDerivacion', models.DateField(blank=True, null=True)),
                ('fechaRequerimiento', models.DateField(blank=True, null=True)),
                ('periodoSolicitado', models.CharField(blank=True, max_length=100, null=True)),
                ('fechaLogistica', models.DateField(blank=True, null=True)),
                ('numOrdenCompra', models.CharField(blank=True, max_length=50, null=True)),
                ('monto', models.IntegerField()),
                ('fechaIngresoAlmacen', models.DateField(blank=True, null=True)),
                ('fechaPago', models.DateField(blank=True, null=True)),
                ('anulacionPedido', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_reg', models.DateTimeField(auto_now=True)),
                ('userOpc', models.CharField(blank=True, max_length=50, null=True)),
                ('userUsuario', models.CharField(blank=True, max_length=50, null=True)),
                ('userLogistica', models.CharField(blank=True, max_length=50, null=True)),
                ('userFinanzas', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
