# Generated by Django 3.1.1 on 2022-08-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0015_delegacionbienesestra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegacionbienesestra',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delegacionbienesestra',
            name='monto',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
