# Generated by Django 3.1.1 on 2022-08-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0017_auto_20220805_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegacionbienesestra',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
    ]
