# Generated by Django 3.1.1 on 2021-11-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0018_incidenciadsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidenciadsi',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='incidenciadsi',
            name='userReg',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
