# Generated by Django 3.1.1 on 2022-08-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0019_auto_20220805_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegacionbienesestra',
            name='pediodoDelegacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
