# Generated by Django 3.1.1 on 2021-11-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0019_auto_20211109_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidenciadsi',
            name='fecha_reg',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
