# Generated by Django 3.1.1 on 2022-09-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0020_delegacionbienesestra_pediododelegacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='maestroMatSap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codSap', models.CharField(max_length=30)),
                ('tipoBienes', models.CharField(max_length=30)),
                ('desProducto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='parNuticion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('pt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cmb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sexo', models.CharField(max_length=30)),
            ],
        ),
    ]
