# Generated by Django 3.1.1 on 2021-11-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0020_incidenciadsi_fecha_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='maestro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codMaestro', models.CharField(max_length=10)),
                ('descripMaestro', models.CharField(max_length=50)),
                ('detalleMaestro', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='incidenciadsi',
            old_name='categoria',
            new_name='problema',
        ),
    ]
