# Generated by Django 3.1.1 on 2021-11-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0021_auto_20211110_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidenciadsi',
            name='problema',
            field=models.CharField(max_length=200),
        ),
    ]
