# Generated by Django 3.1.1 on 2022-09-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0021_maestromatsap_parnuticion'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutricion',
            name='medCali',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
