# Generated by Django 3.1.1 on 2021-11-10 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0022_auto_20211110_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='datosDependencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Asistencial.dependencia'),
            preserve_default=False,
        ),
    ]
