# Generated by Django 3.1.1 on 2022-09-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0022_nutricion_medcali'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutricion',
            name='circuBra',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
