# Generated by Django 3.1.1 on 2021-11-10 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0023_personal_datosdependencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='areaPer',
        ),
    ]
