# Generated by Django 3.1.1 on 2021-11-10 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0024_remove_personal_areaper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambiente',
            old_name='dependencia',
            new_name='datosDependencia',
        ),
    ]
