# Generated by Django 3.1.1 on 2022-09-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0025_auto_20220916_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestromatsap',
            name='tipoBienes',
            field=models.CharField(max_length=70),
        ),
    ]
