# Generated by Django 3.1.1 on 2021-11-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0025_auto_20211110_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambiente',
            old_name='datosDependencia',
            new_name='dependencia',
        ),
        migrations.AddField(
            model_name='personal',
            name='areaPer',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
