# Generated by Django 3.1.1 on 2022-09-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0026_auto_20220916_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegacionbienesestra',
            name='producto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
