# Generated by Django 3.1.1 on 2021-11-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0027_auto_20211110_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidenciadsi',
            name='numTicket',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
