# Generated by Django 3.1.1 on 2022-09-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0027_auto_20220916_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegacionbienesestra',
            name='posiFinaciera',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delegacionbienesestra',
            name='tipoBienEstra',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delegacionbienesestra',
            name='valorTotal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
