# Generated by Django 3.1.1 on 2021-11-10 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0028_incidenciadsi_numticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidenciadsi',
            name='ambiente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Asistencial.ambiente'),
        ),
        migrations.AlterField(
            model_name='incidenciadsi',
            name='clasiSolu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incidenciadsi',
            name='solucion',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
