# Generated by Django 3.1.1 on 2022-09-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0028_auto_20220919_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegacionbienesestra',
            name='fechaEmiOrden',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delegacionbienesestra',
            name='montoOrdenCompra',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delegacionbienesestra',
            name='observaLogistica',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
