# Generated by Django 3.1.1 on 2021-11-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0029_auto_20211110_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidenciadsi',
            name='ambiente',
        ),
        migrations.RemoveField(
            model_name='incidenciadsi',
            name='clasiSolu',
        ),
        migrations.RemoveField(
            model_name='incidenciadsi',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='incidenciadsi',
            name='fecha_reg',
        ),
        migrations.RemoveField(
            model_name='incidenciadsi',
            name='numTicket',
        ),
        migrations.RemoveField(
            model_name='incidenciadsi',
            name='personal',
        ),
        migrations.RemoveField(
            model_name='incidenciadsi',
            name='solucion',
        ),
        migrations.RemoveField(
            model_name='incidenciadsi',
            name='userReg',
        ),
    ]
