# Generated by Django 3.1.1 on 2022-09-20 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0029_auto_20220920_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegacionbienesestra',
            name='montoOrdenCompra',
        ),
    ]
