# Generated by Django 3.1.1 on 2021-11-11 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0030_auto_20211111_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidenciadsi',
            name='clasiSolu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='incidenciadsi',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='incidenciadsi',
            name='fecha_reg',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='incidenciadsi',
            name='numTicket',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidenciadsi',
            name='personal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Asistencial.personal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidenciadsi',
            name='solucion',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='incidenciadsi',
            name='userReg',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
