# Generated by Django 3.1.1 on 2022-09-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0030_remove_delegacionbienesestra_montoordencompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegacionbienesestra',
            name='numDoc',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='delegacionbienesestra',
            name='tipoDoc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
