# Generated by Django 3.1.1 on 2021-12-03 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0031_auto_20211111_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidenciadsi',
            name='maestro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Asistencial.maestro'),
            preserve_default=False,
        ),
    ]
