# Generated by Django 3.1.1 on 2021-12-03 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0032_incidenciadsi_maestro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidenciadsi',
            name='maestro',
        ),
        migrations.AlterField(
            model_name='incidenciadsi',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.maestro'),
        ),
    ]
