# Generated by Django 3.1.1 on 2022-11-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0033_listaespera'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaespera',
            name='distrito',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
