# Generated by Django 3.1.1 on 2022-11-17 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0034_listaespera_distrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='docuContratados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato', models.CharField(blank=True, max_length=100, null=True)),
                ('archivo', models.FileField(null=True, upload_to='formato/')),
                ('estado', models.CharField(blank=True, max_length=5, null=True)),
                ('fecha_reg', models.DateTimeField(auto_now=True)),
                ('usuario_reg', models.CharField(blank=True, max_length=40, null=True)),
                ('fecha_edit', models.DateField(blank=True, null=True)),
                ('cas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.cas')),
            ],
        ),
    ]
