# Generated by Django 3.1.1 on 2021-12-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0034_auto_20211203_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidenciadsi',
            old_name='maestro',
            new_name='estado',
        ),
    ]
