# Generated by Django 3.1.1 on 2021-12-03 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0035_auto_20211203_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienpersonal',
            name='bienpat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.bienpat', unique=True),
        ),
    ]
