# Generated by Django 3.1.1 on 2021-12-06 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0036_auto_20211203_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='bienambiente',
            name='personal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Asistencial.personal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bienambiente',
            name='bienpat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.bienpat', unique=True),
        ),
    ]
