# Generated by Django 3.1.1 on 2021-12-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0037_auto_20211206_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='num_doc',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
