# Generated by Django 3.1.1 on 2022-12-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0037_nutricion_tipopaciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutricion',
            name='obsNutricion',
            field=models.CharField(default='datos de obs', max_length=100),
            preserve_default=False,
        ),
    ]
