# Generated by Django 3.1.1 on 2022-12-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0038_nutricion_obsnutricion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listaespera',
            name='cas',
        ),
        migrations.AddField(
            model_name='listaespera',
            name='casDestino',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listaespera',
            name='casOrigen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
