# Generated by Django 3.1.1 on 2022-12-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0039_auto_20221220_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaespera',
            name='fecha_mod',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listaespera',
            name='fecha_reg',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='listaespera',
            name='user_reg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
