# Generated by Django 3.1.1 on 2022-12-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0040_auto_20221220_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaespera',
            name='user_reg',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
