# Generated by Django 3.1.1 on 2022-01-17 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0040_auto_20211209_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='presAnemia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPres', models.DateField()),
                ('nomNefro', models.CharField(max_length=30)),
                ('medPres', models.CharField(max_length=30)),
                ('dosisPres', models.IntegerField()),
                ('medHiePres', models.CharField(max_length=30)),
                ('dosisHiePres', models.IntegerField()),
                ('viaAdmPres', models.CharField(max_length=10)),
                ('viaAdmHiePres', models.CharField(max_length=10)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='movimientoAnemia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaMotivo', models.DateField()),
                ('razonMotivo', models.CharField(max_length=30)),
                ('obserMotivo', models.CharField(max_length=30)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='exclusionAnemia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaExclu', models.DateField()),
                ('razonExclu', models.CharField(max_length=30)),
                ('ObservaExclu', models.CharField(max_length=30)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='admiAnemia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAdmi', models.DateField()),
                ('nomEnfer', models.CharField(max_length=30)),
                ('medAdmi', models.CharField(max_length=30)),
                ('dosisAdmi', models.IntegerField()),
                ('medHieAdmi', models.CharField(max_length=30)),
                ('dosisHieAdmi', models.IntegerField()),
                ('viaAdm', models.CharField(max_length=10)),
                ('viaAdmHierro', models.CharField(max_length=10)),
                ('presAnemia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.presanemia')),
            ],
        ),
    ]
