# Generated by Django 3.1.1 on 2022-03-07 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0043_biensoftware'),
    ]

    operations = [
        migrations.CreateModel(
            name='bienDetalleMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulgadas', models.CharField(max_length=20)),
                ('bienpat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.bienpat')),
            ],
        ),
    ]
