# Generated by Django 3.1.1 on 2022-03-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0045_nutricion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutricion',
            old_name='diaTurno',
            new_name='frecuencia',
        ),
        migrations.AddField(
            model_name='nutricion',
            name='turno',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
