# Generated by Django 3.1.1 on 2023-01-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0045_auto_20230105_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidenciadsi',
            name='problema',
            field=models.CharField(max_length=1000),
        ),
    ]
