# Generated by Django 3.1.1 on 2023-01-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0046_auto_20230113_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidenciadsi',
            name='solucion',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
