# Generated by Django 3.1.1 on 2022-03-16 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0046_auto_20220310_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='personalVpn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('usuario', models.CharField(max_length=30)),
                ('clave', models.CharField(max_length=30)),
                ('fechaHabilita', models.DateField()),
                ('fechaInstalacion', models.DateField()),
                ('observacion', models.CharField(max_length=200)),
                ('fecha_reg', models.DateTimeField(auto_now=True)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.personal')),
            ],
        ),
    ]
