# Generated by Django 3.1.1 on 2022-03-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0047_personalvpn'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalvpn',
            name='personalAutoriza',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
