# Generated by Django 3.1.1 on 2023-03-13 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0049_paramecentro'),
    ]

    operations = [
        migrations.CreateModel(
            name='parameCentroPuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(max_length=50)),
                ('frecuencia', models.CharField(max_length=100)),
                ('tipoPuesto', models.CharField(max_length=50)),
                ('estado', models.BooleanField()),
                ('fecha_reg', models.DateField(auto_now=True)),
                ('usuario_reg', models.CharField(blank=True, max_length=40, null=True)),
                ('cas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.cas')),
            ],
        ),
    ]
