# Generated by Django 3.1.1 on 2023-03-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0051_paramecentropuesto_numeropuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramecentropuesto',
            name='numeroPuesto',
            field=models.IntegerField(),
        ),
    ]
