# Generated by Django 3.1.1 on 2023-03-16 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0053_cas_distrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramecentropuesto',
            name='usuario_reg',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.CreateModel(
            name='asigCuposPac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAsigCupo', models.DateField()),
                ('fecha_reg', models.DateField(auto_now=True)),
                ('usuario_reg', models.CharField(blank=True, max_length=60, null=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.paciente')),
                ('parameCentroPuesto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.paramecentropuesto')),
            ],
        ),
    ]
