# Generated by Django 3.1.1 on 2023-03-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0054_auto_20230315_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asigcupospac',
            name='fechaAsigCupo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
