# Generated by Django 3.1.1 on 2023-03-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0055_auto_20230316_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='bienhadware',
            name='numeroIpMv',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
