# Generated by Django 3.1.1 on 2023-03-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0056_bienhadware_numeroipmv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asigcupospac',
            name='usuario_reg',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='paramecentro',
            name='usuario_reg',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='paramecentropuesto',
            name='usuario_reg',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
