# Generated by Django 3.1.1 on 2023-03-21 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0056_bienhadware_numeroipmv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asigcupospac',
            name='usuario_reg',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='paramecentro',
            name='usuario_reg',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='paramecentropuesto',
            name='usuario_reg',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='asistenciaPaciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAsisPac', models.DateField()),
                ('fecha_reg', models.DateField(auto_now=True)),
                ('usuario_reg', models.CharField(blank=True, max_length=150, null=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.paciente')),
            ],
        ),
    ]
