# Generated by Django 3.1.1 on 2023-03-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0057_auto_20230321_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciapaciente',
            name='estadoAsistencia',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
