# Generated by Django 3.1.1 on 2023-03-31 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0057_auto_20230330_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='asisPacDiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoAsistencia', models.CharField(max_length=30)),
                ('observaFalta', models.CharField(blank=True, max_length=150, null=True)),
                ('usuario_reg', models.CharField(max_length=150)),
                ('fecha_reg', models.DateField(auto_now=True)),
                ('validacionAsistencia', models.CharField(max_length=150, unique=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.cas')),
            ],
        ),
    ]
