# Generated by Django 3.1.1 on 2023-03-31 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0058_asispacdiario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asispacdiario',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencial.paciente'),
        ),
    ]
