# Generated by Django 3.1.1 on 2023-03-31 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0059_auto_20230331_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asispacdiario',
            name='paciente',
        ),
        migrations.AddField(
            model_name='asispacdiario',
            name='asigCuposPac',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Asistencial.asigcupospac'),
            preserve_default=False,
        ),
    ]
