# Generated by Django 3.1.1 on 2023-05-05 16:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencial', '0062_auto_20230505_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cordePac',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Point(longitude latitude)', null=True, srid=4326, verbose_name='Location in Map'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='latitud',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='longitud',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
